config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/not_authorized'
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'pages#home'
  resources :trades do
    resources :steps, only: %i[show update], controller: 'steps_controllers/trades_steps'
    patch :confirm_presence, on: :member
    get :confirm_screen, on: :member
    patch :realized_trade, on: :member
  end

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/422", to: "errors#unprocessable", via: :all

  resources :profiles do
    member do
      get :invitations
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def invitations
    @user = current_user
    authorize @user
    # receiver_name é o ultmo campo obrigatorio, se ele existe quer dizer que o trade foi completo inteiro
    @trades = Trade.where(buyer: @user).where.not(receiver_name: nil).or(Trade.where(seller: @user).where.not(receiver_name: nil)).order(date: :asc)
  end
end

app/views/profiles/invitations.html.erb
<div class="container content-container">
  <%= link_to "<i class='far fa-arrow-alt-circle-left'></i> Voltar para meu perfil".html_safe, profile_path(current_user), class: "text-decoration-none" %>
  <h1 class="title">Agendamentos</h1>
  <p class="subtitle">Olá <%= @user.first_name %>, confira todos os seus agendamentos e convites.</p>
  <table class="table">
    <thead class="table-head">
      <tr>
        <th scope="col">Encontrar com</th>
        <th scope="col">Item</th>
        <th scope="col">Data</th>
        <th scope="col">Local</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @trades.each do |trade| %>
        <tr>
          <td>
            <% if current_user == trade.buyer %>
              <%= trade.seller ? trade.seller.name : trade.receiver_name %>
            <% else %>
              <%= trade.buyer ? trade.buyer.name : trade.receiver_name %>
            <% end %>
          </td>
          <td><%= link_to trade.seller == current_user ? "Venda de #{trade.item}" : "Compra de #{trade.item}", confirm_screen_trade_path(trade) %></td>
          <td><%= trade.date.strftime("%d/%m/%Y às %H:%M") %></td>
          <td><%= trade.carrefour_unit.name if trade.carrefour_unit%></td>
          <td class="edit-buttons">
            <p>
              <%= link_to '<i class="fas fa-window-close"></i>'.html_safe, trade_path(trade), method: :delete, data: { confirm: "Você tem certeza que deseja cancelar este agendamento ? Essa ação cancelará deifnitivamente o agendamento as duas partes."}, title: "Cancelar" %> 
            </p> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/profiles/show.html.erb
<div class="container d-flex justify-content-center">
        <%= image_tag "icone-usuario.png", class: "profile" %>
</div>
<div class="profile-buttons d-flex justify-content-center">
    <div class="d-flex flex-column">
        <h3>Olá,</hr><br><h3> <%= @user.first_name %></h3>
        <%= link_to "Novo Agendamento", new_trade_path, :class => "btn botoeProflile" %>
        <%= link_to "Agendamentos", invitations_profile_path(:user), :class => "btn botoeProflile" %>
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => "btn botoeProflile" %>
    </div>
</div>