config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/not_authorized'
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'pages#home'
  resources :trades do
    resources :steps, only: %i[show update], controller: 'steps_controllers/trades_steps'
    patch :confirm_presence, on: :member
    get :confirm_screen, on: :member
    patch :realized_trade, on: :member
  end

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/422", to: "errors#unprocessable", via: :all

  resources :profiles do
    member do
      get :invitations
    end
  end
end

app/controllers/steps_controllers/trades_steps_controller.rb
module StepsControllers
  class TradesStepsController < ApplicationController
    include Wicked::Wizard
    require 'uri'
    require 'net/http'

    steps(*Trade.form_steps.keys)

    def show
      @trade = Trade.find(params[:trade_id])
      # On the page of the carrefour unit f1zemos tudo ligado à geoloclização
      @carrefour_units ||= CarrefourUnit.all.order(name: :asc)
      search_for_localisation if step == 'carrefour_unit'
      get_markers_user && get_trade_marker if step == 'invitation'
      @geoloc_success = true if @carrefour_units != CarrefourUnit.all.order(name: :asc)
      authorize @trade
      render_wizard
    end

    def update
      @trade = Trade.find(params[:trade_id])
      authorize @trade
      @trade.assign_attributes(trade_params)
      @trade.author_role == "Vendedor" ? @trade.update(seller: current_user) : @trade.update(buyer: current_user)
      receiver = User.find_by(phone: @trade.receiver_phone)
      @trade.buyer = receiver if @trade.seller == current_user && receiver
      @trade.seller = receiver if @trade.buyer == current_user && receiver
      # If it is the last step
      if @trade.save && step == Trade.form_steps.keys.last
        @trade.created_by_seller? ? @trade.update(seller_accepted: true) : @trade.update(buyer_accepted: true)
        receiver_infos = get_receiver_infos
        WhatsappCreateTradeJob.perform_later(phone: receiver_infos[:receiver_phone], receiver_name: receiver_infos[:receiver_name], sender_user: current_user, trade: @trade, url: @url)
        if receiver_infos[:receiver_email]
          TradeMailer.with(receiver_email: receiver_infos[:receiver_email], receiver_name: receiver_infos[:receiver_name], sender_user: current_user, trade: @trade).created_trade.deliver_later
        end
        # TradeMailer.with(receiver_email: @trade.receiver_email, receiver_name: @trade.receiver_name, sender_user: current_user, trade: @trade).created_trade.deliver_later
        redirect_to(finish_wizard_path, success: "O pedido foi enviado pelo WhatsApp #{@trade.receiver_email ? 'e por email' : ''} para #{@trade.receiver_name}!")
      else
        render_wizard @trade
      end
    end

    private

    def get_receiver_infos
      if current_user == @trade.seller
        receiver_phone = @trade.buyer ? @trade.buyer.phone : @trade.receiver_phone
        receiver_name = @trade.buyer ? @trade.buyer.name : @trade.receiver_name
        receiver_email = @trade.buyer ? @trade.buyer.email : @trade.receiver_email
      else
        receiver_phone = @trade.seller ? @trade.seller.phone : @trade.receiver_phone
        receiver_name = @trade.seller ? @trade.seller.name : @trade.receiver_name
        receiver_email = @trade.seller ? @trade.seller.email : @trade.receiver_email
      end
      @url = confirm_screen_trade_url(@trade)
      { receiver_phone: receiver_phone, receiver_name: receiver_name, receiver_email: receiver_email }
    end

    def trade_params
      params.require(:trade).permit(Trade.form_steps[step]).merge(form_step: step.to_sym)
    end

    def finish_wizard_path
      profile_path(current_user)
    end

    def search_for_localisation
      # Get the localisation of the buyer_cep and seller_cep
      if @trade.seller_cep.present? && @trade.buyer_cep.present?
        # Transform CEP into lat / long
        uri_buyer = URI("https://viacep.com.br/ws/#{@trade.buyer_cep}/json/")
        res_buyer = Net::HTTP.get_response(uri_buyer)
        json_buyer = JSON.parse(res_buyer.body)
        address_buyer = "#{json_buyer['logradouro']}, #{json_buyer['localidade']}"
        @trade.form_step = :location
        if Geocoder.search(address_buyer).first.present?
          coordinates = Geocoder.search(address_buyer).first.coordinates
          @trade.update(lat_buyer: coordinates[0], long_buyer: coordinates[1])
        end

        uri_seller = URI("https://viacep.com.br/ws/#{@trade.seller_cep}/json/")
        res_seller = Net::HTTP.get_response(uri_seller)
        json_seller = JSON.parse(res_seller.body)
        address_seller = "#{json_seller['logradouro']}, #{json_seller['localidade']}"
        if Geocoder.search(address_seller).first.present?
          coordinates = Geocoder.search(address_seller).first.coordinates
          @trade.update(lat_seller: coordinates[0], long_seller: coordinates[1])
        end

        get_markers_user

        if @trade.lat_seller.present? && @trade.long_seller.present? && @trade.lat_buyer.present? && @trade.long_buyer.present?
          order_by_loc(@trade)
        end

        # Generate API MAP
        @markers = @carrefour_units.all.geocoded.map do |unit|
          {
            lat: unit.latitude,
            lng: unit.longitude,
            info_window: render_to_string(partial: "info_window", locals: { unit: unit }),
            id: unit.id
          }
        end
      end
    end

    def order_by_loc(trade)
      # Get the center point between the two users
      center_point = Geocoder::Calculations.geographic_center([[trade.lat_buyer, trade.long_buyer], [trade.lat_seller, trade.long_seller]])
      @carrefour_units = CarrefourUnit.near(center_point, 1_000_000, order: :distance)
    end

    def get_markers_user
      @markers_users = [{
        lat: @trade.lat_seller,
        lng: @trade.long_seller,
        current: @trade.seller == current_user
      },
      {
        lat: @trade.lat_buyer,
        lng: @trade.long_buyer,
        current: @trade.buyer == current_user
      }
    ]
    end

    def get_trade_marker
      @markers = [{
        lat: @trade.carrefour_unit.latitude,
        lng: @trade.carrefour_unit.longitude,
        info_window: render_to_string(partial: "info_window", locals: { unit: @trade.carrefour_unit }),
        id: @trade.carrefour_unit.id
      }]
    end
  end
end

app/views/steps_controllers/trades_steps/_info_window.html.erb
<!-- app/views/flats/_info_window.html.erb -->

<div class='title-popup'><%= unit.name %></div>
<div><%= unit.address %></div>
<div><%= unit.city %></div>
<div><%= unit.suburb %></div>
<div><%= unit.cep %></div>

app/views/steps_controllers/trades_steps/carrefour_unit.html.erb
<div class="container content-container">

  <div class="steps">
    <div class="step active-step"><p>1</p></div>
    <div class="step active-step"><p>2</p></div>
    <div class="step active-step"><p>3</p></div>
    <div class="step"><p>4</p></div>
  </div>
  
  <div data-controller="map" data-action="change->map#selectUnit"> 
    <h1 class="title" data-map-target= 'h1'>A unidade mais próxima é...</h1>
    <p class="subtitle" data-map-target= 'text'>
      O <b><%= @carrefour_units.first.name %></b> fica em <b><%= @carrefour_units.first.address %></b>, mas você pode escolher outro local se preferir.
    </p>
    <%= simple_form_for @trade, url: wizard_path do |f| %>
      <div class="form-group select optional trade_carrefour_unit_id question">
        <label class="select optional" for="trade_carrefour_unit_id">UNIDADE DO CARREFOUR</label>
        <select class="form-control select optional" name="trade[carrefour_unit_id]" id="trade_carrefour_unit_id" data-map-target= 'select'>
          <option value="" label="" data-map-target='firstOption'>Selecione uma unidade</option>
          <% @carrefour_units.each do |unit| %>
            <option value= <%= unit.id %> data-address= <%= unit.address.gsub(' ', '&nbsp') %> ><%= unit.name %></option>
          <% end %>
        </select>
        <% if @geoloc_success %>
          <small class="form-text text-muted">As unidades aparecem na ordem de proximidade entre você e o <%=  @trade.author_role == "Vendedor" ? "comprador" : "vendedor" %>. Você pode selecionar uma unidade na lista para ver aparecer o caminho mais rapido para chegar là.</small>
        <% else %>
          <small class="form-text" style='color: red'>A geolocalização não funcionou com os CEP registrados na etapa anterior, as lojas aparecem por nome (você pode voltar na página anterior para tentar mudar os CEPs).</small>
        <% end %>
      </div>
      <div id="map"
        data-markers="<%= @markers.to_json %>"
        data-markers-users="<%= @markers_users.to_json %>"
        data-mapbox-api-key="<%= Rails.application.credentials.mapbox[:api] %>"
        data-map-target= 'mapbox'
      >
      </div>
      <div class="d-flex justify-content-around">
        <%= link_to 'Voltar', trade_step_path(@trade, "location"), class: "btn btn-primary btn-action rounded-outline-button" %>
        <%= f.submit "Avançar", class: "btn btn-primary rounded-button", id: "avançar" %>
      </div>
    <% end %>
  </div>

  <figure>
    <%= image_tag "carrefour4", class: "propaganda", alt: "propaganda carrefour" %>
  </figure>
</div>

app/views/steps_controllers/trades_steps/infos.html.erb
<div class="container content-container">
  <div class="steps">
    <div class="step active-step"><p>1</p></div>
    <div class="step"><p>2</p></div>
    <div class="step"><p>3</p></div>
    <div class="step"><p>4</p></div>
  </div>
  <h1 class="title">Inicie o seu agendamento</h1>
  <p class="subtitle">Para você ter mais segurança, conte pra gente o que você está comercializando.</p>
  
  <%= simple_form_for(@trade, url: wizard_path, html: { class: "carrefour-form" } ) do |f| %>
    <%= f.input :author_role, label: "VOCÊ É...", as: :select, collection: Trade::ROLE, wrapper_html: { class: "question" } %>
    <%= f.input :item_category_id, as: :select, label: "TIPO DE PRODUTO", collection: ItemCategory.all, wrapper_html: { class: "question" } %>
    <%= f.input :item, label: "NOME DO PRODUTO", wrapper_html: { class: "question" } %>
    <div class="d-flex justify-content-end">
      <%= f.submit "Avançar", class: "btn btn-primary rounded-button unic", id: 'avançar' %>
    </div>
  <% end %>

  <figure>
    <%= image_tag "carrefour2", class: "propaganda", alt: "propaganda carrefour" %>
  </figure>
</div>

app/views/steps_controllers/trades_steps/invitation.html.erb
<div class="container content-container">
  <div class="steps">
    <div class="step active-step"><p>1</p></div>
    <div class="step active-step"><p>2</p></div>
    <div class="step active-step"><p>3</p></div>
    <div class="step active-step"><p>4</p></div>
  </div>

  <h1 class="title">Envie o convite</h1>
  <p class="subtitle">Verifique se a unidade do Carrefour, horário e dia estão corretos e envie o seu convite.</p>

<div class="confirmation-card mb-5">
  <label for="">INFORMAÇÕES DO ENCONTRO</label>
  <p><strong>Unidade: </strong><%=@trade.carrefour_unit.name %></p>
  <p><strong>Endereço: </strong><%= @trade.carrefour_unit.address %></p>
  <p><strong>Data e horário: </strong><%=@trade.date.strftime("%d/%m/%Y às %Hh%M") %></p>
  <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-markers-users="<%= @markers_users.to_json %>"
    data-mapbox-api-key="<%= Rails.application.credentials.mapbox[:api] %>"
    data-map-target = 'mapbox'
    data-draw-routes
  >
</div>

<p class="subtitle mt-5"><strong>Envie o convite deste agendamento:</strong></p>
<%= simple_form_for @trade, url: wizard_path do |f| %>
  <%= f.input :receiver_name, label: "NOME", placeholder: "Nome do convidado", wrapper_html: { class: "question" } %>
  <%= f.input :receiver_phone, label: "TELEFONE", placeholder: "(00) 00000-0000", wrapper_html: { class: "question" }, input_html: {class: "phone_with_ddd" }, hint: 'O outro usuário será avisado por WhatsApp' %>
  <%= f.input :receiver_email, label: "E-MAIL (OPCIONAL)", placeholder: "joao@carrefour.com", wrapper_html: { class: "question" }, hint: 'O outro usuário será avisado por email' %>
  <div class="d-flex justify-content-around">
  <%= link_to 'Voltar', trade_step_path(@trade, "location"), class: "btn btn-primary btn-action rounded-outline-button" %>
  <%= f.submit "Concluir", class: "btn btn-primary rounded-button", id: 'terminar' %>
  </div>
<% end %>

<figure>
<%= image_tag "carrefour5", class: "propaganda5", alt: "propaganda carrefour" %>
</figure>

</div>

app/views/steps_controllers/trades_steps/location.html.erb
<div class="container content-container">
    <div class="steps">
    <div class="step active-step"><p>1</p></div>
    <div class="step active-step"><p>2</p></div>
    <div class="step"><p>3</p></div>
    <div class="step"><p>4</p></div>
  </div>

  <h1 class="title">Localização</h1>
  <p class="subtitle">Preenchendo com os dois CEPs, vamos encontrar a unidade mais perto para as duas partes.</p>
    
  <%= simple_form_for @trade, url: wizard_path do |f| %>
    <%= f.input :buyer_cep, placeholder: "00000-000", label: "SEU CEP", wrapper_html: { class: "question" }, input_html: {class: "cep" } %>
    <%= f.input :seller_cep, label: "CEP DO #{ @trade.author_role == "Vendedor" ? "COMPRADOR" : "VENDEDOR"}", placeholder: "00000-000", wrapper_html: { class: "question" }, input_html: {class: "cep" }  %>
    <div class="calendar">
      <%= f.input :date, as: :string, label: "DATA E HORÁRIO", input_html: {id: "flat_datetime" }, wrapper_html: { class: "question" } %>
    </div>
    <div class="d-flex justify-content-around">
      <%= link_to 'Voltar', trade_step_path(@trade, "infos"), class: "btn btn-primary btn-action rounded-outline-button"  %>
      <%= f.submit "Avançar", class: "btn btn-primary rounded-button", id: 'avançar' %>
    </div>
  <% end %>
  <div class="loading-bckg">
    <div class="box-loading">
      <div class="lds-ripple">
        <div></div>
        <div></div>
      </div>
      <p>Estamos procurando as lojas Carrefour mais perto de vocês</p>
    </div>
  </div>

  <figure>
    <%= image_tag "carrefour1", class: "propaganda", alt: "propaganda carrefour" %>
  </figure>
</div>