config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/not_authorized'
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'pages#home'
  resources :trades do
    resources :steps, only: %i[show update], controller: 'steps_controllers/trades_steps'
    patch :confirm_presence, on: :member
    get :confirm_screen, on: :member
    patch :realized_trade, on: :member
  end

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/422", to: "errors#unprocessable", via: :all

  resources :profiles do
    member do
      get :invitations
    end
  end
end

app/views/trade_steps/new.html.erb
<%= simple_form_for(@trade, url: trade_steps_path) do |f| %>
  <%= f.input :author, lable: "Nesta transação, você é o:", as: :radio_buttons, collection: ["Vendedor", "Comprador"] %>
  <%= f.input :item_category_id, as: :select, label: "A categoria do item é:", collection: @item_categories %>
  <%= f.input :item, label: "O item transacionado é:" %>
  <%= f.submit "Avançar" %>
<% end %>

app/views/trade_steps/trade_details.html.erb
<%= simple_form_for @trade do |f| %>
  <%= f.input :created_by, lable: "Nesta transação, você é o:", as: :radio_buttons, collection: ["Vendedor", "Comprador"] %>
  <%= f.association :item_category, as: :select, label: "A categoria do item é:", label_method: :name, collection: @item_categories %>
  <%= f.input :item, label: "O item transacionado é:" %>
  <%= f.submit "Avançar" %>
<% end %>