config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/not_authorized'
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'pages#home'
  resources :trades do
    resources :steps, only: %i[show update], controller: 'steps_controllers/trades_steps'
    patch :confirm_presence, on: :member
    get :confirm_screen, on: :member
    patch :realized_trade, on: :member
  end

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/422", to: "errors#unprocessable", via: :all

  resources :profiles do
    member do
      get :invitations
    end
  end
end

app/models/trade.rb
class Trade < ApplicationRecord

  belongs_to :carrefour_unit, optional: true
  belongs_to :item_category, optional: true
  belongs_to :seller, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :author, class_name: "User"
  before_save :clean_phone

  ROLE = ["Vendedor", "Comprador"]

  enum form_steps: {
    infos: %i[item item_category_id author_role],
    location: %i[date buyer_cep seller_cep lat_seller long_seller lat_buyer long_buyer],
    carrefour_unit: %i[carrefour_unit_id],
    invitation: %i[receiver_name receiver_phone receiver_email]
  }
  attr_accessor :form_step

  def confirmed?
    buyer_accepted && seller_accepted
  end

  def invited
    author == buyer ? seller : buyer
  end

  def created_by_seller?
    author_role == "Vendedor"
  end

  with_options if: -> { required_for_step?(:infos) } do
    validates :item, presence: true
    validates :item_category_id, presence: true
    validates :author, presence: true
  end

  with_options if: -> { required_for_step?(:location) } do
    validates :date, presence: true
    validates :buyer_cep, presence: true
    validates :seller_cep, presence: true
    validate :verify_cep
  end

  with_options if: -> { required_for_step?(:carrefour_unit) } do
    validates :carrefour_unit_id, presence: true
  end

  with_options if: -> { required_for_step?(:invitation) } do
    validates :receiver_name, presence: true
    validates :receiver_phone, presence: true
  end

  def required_for_step?(step)
    # All fields are required if no form step is present
    return true if form_step.nil?

    # All fields from previous steps are required
    ordered_keys = self.class.form_steps.keys.map(&:to_sym)
    !!(ordered_keys.index(step) <= ordered_keys.index(form_step))
  end

  
  def clean_phone
    self.receiver_phone = self.receiver_phone.delete("(").delete(")").delete("-") if self.receiver_phone.present?
  end

  def verify_cep
    regexp_cep = /^\d{5}(-?)\d{3}$/

    unless buyer_cep.present? && buyer_cep.match?(regexp_cep)
      errors.add :buyer_cep, "não é valido"
    end

    unless seller_cep.present? && seller_cep.match?(regexp_cep)
      errors.add :seller_cep, "não é valido"
    end

  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: %i[edit destroy update confirm_presence confirm_screen set_reminder realized_trade]
  before_action :get_url, only: %i[update destroy confirm_presence]
  before_action :get_markers_users, only: %i[confirm_screen edit update]
  before_action :get_uniq_marker, only: %i[confirm_screen]
  before_action :trade_params, only: [:realized_trade]

  def index
    @trades = policy_scope(Trade)
    authorize @trades
  end

  def new
    @trade = Trade.new
    @trade.author = current_user
    authorize @trade
    # We save an instance of the trade in database even if not valid
    @trade.save!(validate: false)
    # We redirect to trade_step_path in order to begin the Wizard form
    redirect_to trade_step_path(@trade, Trade.form_steps.keys.first)
    authorize @trade
  end

  def edit
    order_by_loc
    @carrefour_units = nil if @carrefour_units.empty?
    @carrefour_units ||= CarrefourUnit.all
    get_markers
  end

  def update
    @carrefour_units ||= CarrefourUnit.all
    get_markers
    if @trade.update(trade_params)
      if current_user == @trade.seller
        @trade.update(seller_accepted: true, buyer_accepted: false)
        # TradeMailer.with(receiver_email: receiver_email, receiver_name: receiver_name, sender_user: current_user, trade: @trade).update_trade.deliver_later
      else
        @trade.update(seller_accepted: false, buyer_accepted: true)
        # TradeMailer.with(receiver_email: receiver_email, receiver_name: receiver_name, sender_user: current_user, trade: @trade).update_trade.deliver_later
      end
      receiver_infos = get_receiver_infos
      WhatsappUpdateTradeJob.perform_later(phone: receiver_infos[:receiver_phone], receiver_name: receiver_infos[:receiver_name], sender_user: current_user, trade: @trade, url: @url)
      redirect_to(confirm_screen_trade_path(@trade), success: "As informações foram modificadas com sucesso, uma mensagem WhatsApp foi mandado para #{receiver_infos[:receiver_name]} para confirmação !")
    else
      render :edit
    end
  end

  def destroy
    receiver_infos = get_receiver_infos
    if @trade.destroy
      WhatsappDestroyTradeJob.perform_later(phone: receiver_infos[:receiver_phone], receiver_name: receiver_infos[:receiver_name], sender_user: current_user, trade: @trade, url: @url)
      redirect_to(invitations_profile_path, success: "Você cancelou esse agendamento, uma mensagem foi mandada para avisar #{receiver_infos[:receiver_name]}")
    else
      render 'profiles/invitations'
    end
  end


  def confirm_presence
    current_user == @trade.buyer ? @trade.update(buyer_accepted: true) : @trade.update(seller_accepted: true)
    receiver_infos = get_receiver_infos
    if @trade.buyer_accepted == true && @trade.seller_accepted == true
      WhatsappConfirmTradeJob.perform_now(phone: receiver_infos[:receiver_phone], receiver_name: receiver_infos[:receiver_name], sender_user: current_user, trade: @trade, url: @url)
    end
    # TradeMailer.with(receiver_email: @trade.receiver_email, receiver_name: @trade.receiver_name, sender_user: current_user, trade: @trade).confirm_trade.deliver_later
    redirect_to(confirm_screen_trade_path(@trade), success: "Você confirmou a sua presença para esse encontro !")
  end


  def set_reminder
    # WhatsappRememberTradeJob.set(wait_until: @trade.date.advance(days: -1)).perform_later.(phone: @trade.buyer.phone, name: @trade.buyer.first_name, other_trader: @trade.seller.first_name, trade: @trade, url: confirm_screen_trade_url(@trade))
    # WhatsappRememberTradeJob.set(wait_until: @trade.date.advance(days: -1)).perform_later.(phone: @trade.seller.phone, name: @trade.seller.first_name, other_trader: @trade.buyer.first_name, trade: @trade, url: confirm_screen_trade_url(@trade))
  end

  def confirm_screen
    @qr_code = RQRCode::QRCode.new("http://segunda-mao-carrefour.herokuapp.com/trades/#{@trade.id}/confirm_screen")
    @svg = @qr_code.as_svg(
      standalone: true,
      use_path: true,
      viewbox: true,
      offset: 15
    )
  end

  def realized_trade
    if trade_params[:realized] == 'realized'
      @trade.update(realized: true)
    elsif trade_params[:realized] == 'cancelled'
      @trade.update(realized: false)
    end
    redirect_to confirm_screen_trade_path(@trade), succes: "O agendamento foi atualizado com sucesso"
  end

  private
  def get_markers_users
    @markers_users = [{
      lat: @trade.lat_seller,
      lng: @trade.long_seller,
      current: @trade.seller == current_user
    },
    {
      lat: @trade.lat_buyer,
      lng: @trade.long_buyer,
      current: @trade.buyer == current_user
    }]
  end

  def get_uniq_marker
    # Generate API MAP
    @markers = [{
      lat: @trade.carrefour_unit.latitude,
      lng: @trade.carrefour_unit.longitude,
      info_window: render_to_string(partial: "steps_controllers/trades_steps/info_window", locals: { unit: @trade.carrefour_unit }),
      id: @trade.carrefour_unit.id
    }]
  end

  def get_markers
    @markers = @carrefour_units.all.geocoded.map do |unit|
      {
        lat: unit.latitude,
        lng: unit.longitude,
        info_window: render_to_string(partial: "steps_controllers/trades_steps/info_window", locals: { unit: unit }),
        id: unit.id
      }
    end
  end

  def order_by_loc
    # Get the center point between the two users
    center_point = Geocoder::Calculations.geographic_center([[@trade.lat_buyer, @trade.long_buyer], [@trade.lat_seller, @trade.long_seller]])
    @carrefour_units = CarrefourUnit.near(center_point, 1_000_000, order: :distance)
  end

  def get_receiver_infos
    if current_user == @trade.seller
      receiver_phone = @trade.buyer ? @trade.buyer.phone : @trade.receiver_phone
      receiver_name = @trade.buyer ? @trade.buyer.name : @trade.receiver_name
      receiver_email = @trade.buyer ? @trade.buyer.email : @trade.receiver_email
    else
      receiver_phone = @trade.seller ? @trade.seller.phone : @trade.receiver_phone
      receiver_name = @trade.seller ? @trade.seller.name : @trade.receiver_name
      receiver_email = @trade.seller ? @trade.seller.email : @trade.receiver_email
    end
    { receiver_phone: receiver_phone, receiver_name: receiver_name, receiver_email: receiver_email }
  end

  def set_trade
    @trade = Trade.find(params[:id])
    authorize @trade
  end

  def trade_params
    params.require(:trade).permit(:carrefour_unit_id, :date, :realized)
  end

  def get_url
    @url = confirm_screen_trade_url(@trade)
  end
end

app/views/trades/confirm_presence.html.erb
<div class="container content-container">
  
  <%# TODO: Evento já foi realizado: solicitar confirmação de presença %>
  <% if DateTime.now > @trade.date %>
    <h1>Este encontro já foi realizado</h1>
    <p class="subtitle">Confirme se este evento já foi realizado.</p>
    <button class="btn btn-primary">Sim, já realizei este encontro</button>
    <button class="btn btn-outline-primary">Este evento foi cancelado</button>
  
  <% else %> <%# Evento ainda não foi realizado %>
    <% if @trade.author == current_user %>
    <h1>Você tem um agendamento!</h1>
      <p class="subtitle mb-5"><strong>Olá <%= current_user ? current_user.first_name : @trade.receiver_name %></strong>, você tem um agendamento marcado para a transação do <%= @trade.item %> no 2ª Mão Point. Confira a data, horário e local.
    <% else %>
    <h1>Você recebeu um convite!</h1>  
      <p class="subtitle mb-5"><strong>Olá <%= current_user ? current_user.first_name : @trade.receiver_name %></strong>, você recebeu um convite para realizar a transação do <%= @trade.item %>. Confira a data, horário e local.
    <% end %>
    
    <div class="mb-5 text-center">
      <p><strong>Unidade Carrefour:</strong></p>
      <p><%= @trade.carrefour_unit.name %></p>
      <p><%= @trade.carrefour_unit.address %></p>
      <p><%= @trade.carrefour_unit.suburb %> - <%= @trade.carrefour_unit.city %></p>
      <p>CEP: <%= @trade.carrefour_unit.cep %></p>
    </div>
    <div class="mb-5 text-center">
      <p><strong>Data e horário:</strong></p>
      <p>Dia: <%= @trade.date.strftime("%d/%m/%Y") %></p>
      <p>Horário: <%= @trade.date.strftime("%H:%M") %></p>
    </div>
    
    <div class="d-flex justify-content-around">      
        <%= link_to "Reagendar", edit_trade_path(@trade), class: "btn btn-outline-primary" %>
        <%# TODO: se a outra parte reagendar, ela vira author? Se não, precisamos mostrar novamente o botão de Confirmar caso haja reagendamento do convidado %>
        <% if (current_user == @trade.buyer && @trade.buyer_accepted == false) || (current_user == @trade.seller && @trade.seller_accepted == false) %> 
          <%= link_to "Confirmar presença", confirm_presence_trade_path(@trade), method: :patch, class: "btn btn-primary" %>
        <% else %>
          <button class="btn btn-success disabled">Confirmado</button>
        <% end %>
    </div>

  <% end %>
</div>

app/views/trades/confirm_screen.html.erb
<div class="container content-container">
  <%= link_to "<i class='far fa-arrow-alt-circle-left'></i> Voltar para os agendamentos".html_safe, invitations_profile_path(current_user), class: "text-decoration-none" %>
  <%# TODO: Evento já foi realizado: solicitar confirmação de presença %>
  <% if DateTime.now > @trade.date %>
    <h1 class="title" style="margin-top:2rem;">Este encontro já passou</h1>
    <% if @trade.realized.nil? %>
      <p class="subtitle">Confirme se este evento já foi realizado.</p>
      <div class="d-flex flex-column justify-content-center align-items-center">
        <%= form_with(model: @trade, url: realized_trade_trade_path, data: {confirm: 'Não será mais possível modificar essa informação depois'}) do |f| %>
          <%= f.hidden_field :realized, as: :hidden, value: 'realized' %>
          <%= f.submit 'Sim, já realizei este encontro', class: 'btn btn-primary rounded-button stacked-button' %>
        <% end %>
        <%= form_with(model: @trade, url: realized_trade_trade_path, data: {confirm: 'Não será mais possível modificar essa informação depois'}) do |f| %>
          <%= f.hidden_field :realized, as: :hidden, value: 'cancelled' %>
          <%= f.submit 'Este evento foi cancelado', class: 'btn btn-primary rounded-button canceled stacked-button' %>
        <% end %>
      </div>
    <% elsif @trade.realized %>
      <div class="d-flex align-items-center flex-column">
        <div class="big-icon green">
          <i class="far fa-check-circle"></i>
        </div>
        <p>Esse encontro foi realizado com sucesso</p>
      </div>
    <% else %>
      <div class="d-flex align-items-center flex-column">
        <div class="big-icon red">
          <i class="fas fa-ban"></i>
        </div>
        <p>Infelizmente esse encontro foi cancelado</p>
      </div>
    <% end %>
  
  <% else %> <%# Evento ainda não foi realizado %>
    <% if @trade.author == current_user %>
    <h1 class="title" style="margin-top:2rem;">Você tem um agendamento!</h1>
      <p class="subtitle mb-5"><strong>Olá <%= current_user ? current_user.first_name : @trade.receiver_name %></strong>, você tem um agendamento marcado para a seguinte transação : <%= @trade.item %> no 2ª Mão Point. Confira a data, horário e local.
    <% else %>
    <h1 class="title" style="margin-top: 2rem;">Você recebeu um convite!</h1>  
      <p class="subtitle mb-5"><strong>Olá <%= current_user ? current_user.first_name : @trade.receiver_name %></strong>, você recebeu um convite para a seguinte transação : <%= @trade.item %>. Confira a data, horário e local.
    <% end %>
    
    <div class="confirmation-card mb-5 text-center">
      <p><strong>Unidade Carrefour:</strong> <%= @trade.carrefour_unit.name %></p>
      <p><strong>Endereço:</strong> <%= @trade.carrefour_unit.address %></p>
      <p><strong>Bairro</strong> <%= @trade.carrefour_unit.suburb %> - <%= @trade.carrefour_unit.city %></p>
      <p><strong>CEP:</strong> <%= @trade.carrefour_unit.cep %></p>
      <p><strong>Data e horário:</strong> <%= @trade.date.strftime("%d/%m/%Y, às %H:%M") %></p>
      <div id="map"
        data-markers="<%= @markers.to_json %>"
        data-markers-users="<%= @markers_users.to_json %>"
        data-mapbox-api-key="<%= Rails.application.credentials.mapbox[:api] %>"
        data-map-target= 'mapbox'
        class='mb-3'
        data-draw-routes
      >
    </div>


    <% if @trade.confirmed? %>
      <div class="confirmation-card d-flex flex-column align-items-center mb-5">
        <p class="mt-4 subtitle">Para sua segurança, você deve apresentar este QR Code ao chegar no 2ª Mão Point. Você também receberá por Whatsapp no dia do encontro.</p>
          <%= @svg.html_safe %>
      </div>
    <% else %>
      <div class="confirmation-card d-flex flex-column align-items-center mb-5">
        <p style='color: red;'>Você receberá um QR code uma vez que as duas partes tenham aceitado o agendamento.</p>
      </div>
    <% end %>
    
    <div class="d-flex justify-content-around align-items-center">      
        <%= link_to "Reagendar", edit_trade_path(@trade), class: "rounded-outline-button" %>
        <%# TODO: se a outra parte reagendar, ela vira author? Se não, precisamos mostrar novamente o botão de Confirmar caso haja reagendamento do convidado %>
        <% if (current_user == @trade.buyer && @trade.buyer_accepted == false) || (current_user == @trade.seller && @trade.seller_accepted == false) %> 
          <%= link_to "Confirmar presença", confirm_presence_trade_path(@trade), method: :patch, class: "btn btn-primary rounded-button" %>
        <% elsif (current_user == @trade.buyer && @trade.seller_accepted == false) || (current_user == @trade.seller && @trade.buyer_accepted == false) %>
          <div class="btn btn-warning disabled rounded-button-waiting">Aguardando confirmação</div>
        <% elsif @trade.confirmed? %>
          <div class="btn btn-success rounded-button-confirmed">Confirmado</div>
        <% end %>
    </div>

  <% end %>
</div>

app/views/trades/edit.html.erb
<div class="container content-container">
  <h1 class="title">Reagendamento</h1>
  <p class="subtitle">Após a mudança de data ou unidade, enviaremos uma mensagem para a outra parte da negociação para confirmação.</p>
  <div data-controller="map"> 
    <%= simple_form_for @trade, method: :put do |f| %>
      <%= f.input :date, label: "Sua data de agendamento atual é", as: :string, input_html: { id: 'flat_datetime' }, wrapper_html: { class: 'question'} %>
      <div class="form-group select optional trade_carrefour_unit_id question">
        <select class="form-control select optional" name="trade[carrefour_unit_id]" id="trade_carrefour_unit_id" data-map-target= 'select' data-action="change->map#selectUnit">
          <% @carrefour_units.each do |unit| %>
            <option value= <%= unit.id %> <%= @trade.carrefour_unit.id == unit.id ? 'selected' : '' %> data-address= <%= unit.address.gsub(' ', '&nbsp') %>><%= unit.name %></option>
          <% end %>
        </select>
      </div>
      <h5 class='text-center' data-map-target= 'h1'>Você escolheu...</h5>
      <p class="subtitle" data-map-target= 'text'>
        O <b><%= @trade.carrefour_unit.name %></b> fica em <b><%= @trade.carrefour_unit.address %></b>, mas você pode escolher outro local se preferir.
      </p>
      <div 
        id="map"
        data-markers="<%= @markers.to_json %>"
        data-markers-users="<%= @markers_users.to_json %>"
        data-mapbox-api-key="<%= Rails.application.credentials.mapbox[:api] %>"
        data-map-target= 'mapbox'
        class='mb-3'
      >
      </div>
      <div class="d-flex justify-content-between">
        <%= link_to "Voltar", invitations_profile_path(current_user), class: "btn btn-primary rounded-outline-button btn-action" %>
        <%= f.submit "Alterar", class: "btn btn-primary rounded-button", data: { confirm: "Você tem certeza que deseja modificar este agendamento? Uma mensagem será enviada para o otro usúario pedindo para confirmar as novas informações." } %>
      </div>
    <% end %>
  </div>
</div>

app/views/trades/invitation.html.erb
<h1>Confirme os dados e faça o convite</h1>
<p>Confirme a unidade, dia e horário escolhidos para efetivar a negociação.</p>

<h2>Unidade Carrefour:</h2>
<p><%= @trade.carrefour_unit.name %></p>

<h2>Data e horário</h2>
<p><%= @trade.date %></p>

<h2>Envie o convite deste agendamento:</h2>
<%= simple_form_for(@trade, url: wizard_path) do |f| %>
  <%= f.input :receiver_email, label: "E-mail convite" %>
  <%= f.submit "Avançar" %>
<% end %>

<%= link_to 'Back', :back %>

app/views/trades/new.html.erb
<%= simple_form_for(@trade, url: trades_path) do |f| %>
  <%= f.input :author, lable: "Nesta transação, você é o:", as: :radio_buttons, collection: ["Vendedor", "Comprador"] %>
  <%= f.association :item_category, as: :select, label: "A categoria do item é:", collection: @item_categories %>
  <%= f.input :item, label: "O item transacionado é:" %>
  <%= f.submit "Avançar" %>
<% end %>